### ISSUE TITLE
RuntimeError in relation ranking's train step

### ISSUE THREAD

**Issue by lixiang1991** [quyingqi/kbqa-ar-smcnn#3]
Hi, When I was training the relation ranking model, the error code shows as follow:
```
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    pos_score, neg_score = model(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/model.py", line 213, in forward
    pos_score1 = self.cal_score(outputs, seq_len, pos_rel1_embed, neg_size)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/model.py", line 115, in cal_score
    seq_att, weight = self.question_attention.forward(rel_embed, outputs)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 54, in forward
    weight = self.attention(x, seq, lengths)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 40, in attention
    score = self._score(x, seq)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 108, in _score
    _seq = self.pack_seq(seq)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 81, in pack_seq
    return seq.view(seq.size(0) * seq.size(1), -1)
RuntimeError: invalid argument 2: View size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /pytorch/aten/src/THC/generic/THCTensor.c:276
```

And the messages before the error shows as follow:
```
Note: You are using GPU for training
load word vocab, size: 63112
load relation vocab, size: 2
load train data, batch_num: 1131	batch_size: 64
load valid data, batch_num: 163	batch_size: 64
Namespace(batch_size=64, birnn=True, channel_size=8, clip_gradient=0.6, conv_kernel_1=3, conv_kernel_2=3, cuda=True, d_hidden=128, d_rel_embed=256, d_word_embed=300, dev=False, dev_every=600, dropout_prob=0.3, epochs=30, fix_emb=True, gpu=0, log_every=100, loss_margin=1.0, lr=0.0005, n_cells=4, n_layers=2, neg_size=50, patience=5, pool_kernel_1=21, pool_kernel_2=1, predict=False, rel_maxlen=17, rel_vocab_file='../vocab/vocab.rel.sep.pt', results_path='results', resume_snapshot=None, rnn_type='gru', save_every=4500, save_path='saved_checkpoints', seed=1111, seq_maxlen=21, test=False, test_file='data/test.relation_ranking.pt', train_file='data/train.relation_ranking.pt', trained_model='', valid_file='data/valid.relation_ranking.pt', vector_cache='/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/../input_vectors.pt', vocab_file='../vocab/vocab.word&rel.pt', word_normalize=False, word_vectors='../vocab/glove.42B.300d.txt', write_res=False, write_score=False)
Shift model to GPU
word_embed.emb_luts.0.weight torch.Size([63112, 300])
rel1_embed.emb_luts.0.weight torch.Size([3523, 256])
rel2_embed.emb_luts.0.weight torch.Size([4658, 256])
rnn.weight_ih_l0 torch.Size([384, 300])
rnn.weight_hh_l0 torch.Size([384, 128])
rnn.bias_ih_l0 torch.Size([384])
rnn.bias_hh_l0 torch.Size([384])
rnn.weight_ih_l0_reverse torch.Size([384, 300])
rnn.weight_hh_l0_reverse torch.Size([384, 128])
rnn.bias_ih_l0_reverse torch.Size([384])
rnn.bias_hh_l0_reverse torch.Size([384])
rnn.weight_ih_l1 torch.Size([384, 256])
rnn.weight_hh_l1 torch.Size([384, 128])
rnn.bias_ih_l1 torch.Size([384])
rnn.bias_hh_l1 torch.Size([384])
rnn.weight_ih_l1_reverse torch.Size([384, 256])
rnn.weight_hh_l1_reverse torch.Size([384, 128])
rnn.bias_ih_l1_reverse torch.Size([384])
rnn.bias_hh_l1_reverse torch.Size([384])
question_attention.layer.layer1.weight torch.Size([256, 512])
question_attention.layer.layer2.weight torch.Size([1, 256])
bilinear.weight torch.Size([1, 256, 256])
seq_out.1.weight torch.Size([256, 256])
seq_out.1.bias torch.Size([256])
conv.0.weight torch.Size([8, 1, 3, 3])
conv.0.bias torch.Size([8])
fc.0.weight torch.Size([20, 136])
fc.0.bias torch.Size([20])
fc.3.weight torch.Size([1, 20])
fc.3.bias torch.Size([1])
fc1.0.weight torch.Size([20, 168])
fc1.0.bias torch.Size([20])
fc1.3.weight torch.Size([1, 20])
fc1.3.bias torch.Size([1])
fc2.0.weight torch.Size([1, 4])
fc2.0.bias torch.Size([1])
  Time Epoch Iteration Progress    (%Epoch)   Loss       Accuracy  Dev/Accuracy
Traceback (most recent call last):
  File "train.py", line 109, in <module>
    pos_score, neg_score = model(batch)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/model.py", line 213, in forward
    pos_score1 = self.cal_score(outputs, seq_len, pos_rel1_embed, neg_size)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/model.py", line 115, in cal_score
    seq_att, weight = self.question_attention.forward(rel_embed, outputs)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 54, in forward
    weight = self.attention(x, seq, lengths)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 40, in attention
    score = self._score(x, seq)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 108, in _score
    _seq = self.pack_seq(seq)
  File "/home/xxs344/lx/kbqa-ar-smcnn/relation_ranking/attention.py", line 81, in pack_seq
    return seq.view(seq.size(0) * seq.size(1), -1)
RuntimeError: invalid argument 2: View size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /pytorch/aten/src/THC/generic/THCTensor.c:276

```

And training and predicting steps for entity detection model worked well.
Any help will be greatly appreciated!

**Comment by nlpjoe** [comment]
@lixiang1991 I have the same problem, Did you find a solution?

**Comment by nlpjoe** [comment]
@lixiang1991 change 
```
return seq.view(seq.size(0) * seq.size(1), -1)
```
into
```
return seq.contiguous().view(seq.size(0) * seq.size(1), -1)
```

you can fix this bug to go to the next bug

**Comment by nlpjoe** [comment]
@lixiang1991 it works now

**Comment by lixiang1991** [comment]
@nlpjoe you are right! Thanks!
it really works

**Comment by lixiang1991** [comment]
@nlpjoe do you mean that the next bug is at this code?
```
stride1 = 1.0 * max_len1 / len1_one
stride2 = 1.0 * max_len2 / len2_one
```
I fix it by change into:
```
stride1 = 1.0 * max_len1 / len1_one.item()
stride2 = 1.0 * max_len2 / len2_one.item()
```

**Comment by lixiang1991** [comment]
And there is an another bug in the predict.py:
```
pred_rel_scores = sorted(zip(neg_rel, neg_score), key=lambda i:i[1], reverse=True)
```
I fix it by change into:
```
if neg_score.size==1:
        pred_rel_scores =(neg_rel[0],neg_score.item())
    else:
        pred_rel_scores = sorted(zip(neg_rel, neg_score), key=lambda i:i[1], reverse=True)
```

**Comment by nlpjoe** [comment]
hello guy, my final result on FB2M is 76.7,much worse than the 77.9 in the paper, how about you?
my result is below:
```
load test data, batch_num: 20679	batch_size: 1
test	accuracy: 76.713724	correct: 15813	total: 20613
rel_acc:  90.06852766300514 17875 19846
recall:  89.97279048674795 17856 19846
single_acc:  75.19399375188955 14923 19846
```
